### ISSUE TITLE
Support 2D FITS images

### ISSUE THREAD

**Issue by gtudisco** [VisIVOLab/ParaviewFitsReader#3]
Add support for 2D FITS images.

**Comment by fvitello** [comment]
The tool should detect if the selected fits is a 2D or a 3D reading the header of the file.  
The reader should employ MPI to parallelize the reading of the fits

**Comment by Pietersielie** [comment]
Commit a7ecd3c works for displaying 2D FITS images in the paraview client. It reuses the existing code almost exclusively, so should employ MPI (assuming the 3D reader uses MPI).
